import { BarberShop, Review, PricingPlan, DashboardStats, AdminStats, Invoice, Notification } from "@/types";

const shopImages = [
  "https://images.unsplash.com/photo-1585747860019-8027e1fdb9c5?w=800&q=80",
  "https://images.unsplash.com/photo-1503951914875-452bfac3476b?w=800&q=80",
  "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80",
  "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&q=80",
  "https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&q=80",
  "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80",
];

const avatars = [
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
  "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80",
  "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80",
];

export const mockBarberShops: BarberShop[] = [
  {
    id: "1",
    name: "Royal Cuts Barbershop",
    slug: "royal-cuts-barbershop",
    description: "Premium barbershop in the heart of Gulberg, Lahore. We specialize in modern and classic hairstyles with a luxury grooming experience.",
    owner: "Ahmed Khan",
    phone: "+92 300 1234567",
    whatsapp: "+92 300 1234567",
    email: "royalcuts@email.com",
    address: "Shop 12, Gulberg III, Main Boulevard",
    city: "Lahore",
    area: "Gulberg",
    latitude: 31.5204,
    longitude: 74.3587,
    rating: 4.8,
    totalReviews: 234,
    images: shopImages,
    coverImage: shopImages[0],
    logo: avatars[0],
    isVerified: true,
    isOpen: true,
    isPremium: true,
    badges: ["Top Rated", "Premium", "Verified"],
    createdAt: "2024-01-15",
    monthlyVisits: 1250,
    qrScans: 340,
    services: [
      { id: "s1", name: "Classic Haircut", category: "Haircut", price: 500, duration: 30, description: "Traditional haircut with modern finishing", isPopular: true },
      { id: "s2", name: "Premium Haircut", category: "Haircut", price: 800, duration: 45, description: "Premium styling with hair wash and blow dry", isPopular: true },
      { id: "s3", name: "Beard Trim", category: "Beard Trim", price: 300, duration: 20, description: "Professional beard shaping and trimming", isPopular: true },
      { id: "s4", name: "Clean Shave", category: "Shave", price: 250, duration: 20, description: "Hot towel clean shave experience", isPopular: false },
      { id: "s5", name: "Hair Color", category: "Hair Color", price: 1500, duration: 60, description: "Professional hair coloring with premium products", isPopular: false },
      { id: "s6", name: "Facial", category: "Facial", price: 800, duration: 40, description: "Deep cleansing facial treatment", isPopular: true },
      { id: "s7", name: "Head Massage", category: "Head Massage", price: 400, duration: 25, description: "Relaxing head and scalp massage", isPopular: false },
      { id: "s8", name: "Kids Haircut", category: "Kids Haircut", price: 350, duration: 25, description: "Fun haircuts for kids under 12", isPopular: false },
    ],
    team: [
      { id: "t1", name: "Ahmed Khan", role: "Master Barber", specialties: ["Fades", "Beard Design"], experience: 12, image: avatars[0] },
      { id: "t2", name: "Bilal Hussain", role: "Senior Barber", specialties: ["Classic Cuts", "Hair Color"], experience: 8, image: avatars[1] },
      { id: "t3", name: "Usman Ali", role: "Barber", specialties: ["Kids Cuts", "Shaving"], experience: 5, image: avatars[2] },
    ],
    timings: [
      { day: "Monday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Tuesday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Wednesday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Thursday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Friday", openTime: "02:00 PM", closeTime: "10:00 PM", isClosed: false },
      { day: "Saturday", openTime: "10:00 AM", closeTime: "11:00 PM", isClosed: false },
      { day: "Sunday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
    ],
  },
  {
    id: "2",
    name: "Sultan's Grooming Lounge",
    slug: "sultans-grooming-lounge",
    description: "Luxury grooming lounge offering premium barber services in DHA Karachi. Experience the art of traditional grooming with modern techniques.",
    owner: "Sultan Mehmood",
    phone: "+92 321 9876543",
    whatsapp: "+92 321 9876543",
    email: "sultans@email.com",
    address: "Plot 42, Khayaban-e-Bukhari, DHA Phase 6",
    city: "Karachi",
    area: "DHA",
    latitude: 24.8607,
    longitude: 67.0011,
    rating: 4.9,
    totalReviews: 412,
    images: [shopImages[1], shopImages[2], shopImages[3], shopImages[4]],
    coverImage: shopImages[1],
    logo: avatars[1],
    isVerified: true,
    isOpen: true,
    isPremium: true,
    badges: ["Top Rated", "Premium", "Verified", "Featured"],
    createdAt: "2023-06-20",
    monthlyVisits: 2100,
    qrScans: 580,
    services: [
      { id: "s9", name: "Signature Haircut", category: "Haircut", price: 1200, duration: 45, description: "Sultan's signature styling experience", isPopular: true },
      { id: "s10", name: "Royal Beard Styling", category: "Beard Trim", price: 600, duration: 30, description: "Premium beard design and grooming", isPopular: true },
      { id: "s11", name: "Hot Towel Shave", category: "Shave", price: 500, duration: 30, description: "Classic hot towel straight razor shave", isPopular: true },
      { id: "s12", name: "Keratin Treatment", category: "Hair Treatment", price: 3000, duration: 90, description: "Professional keratin hair treatment", isPopular: false },
      { id: "s13", name: "Bridal Groom Package", category: "Bridal Groom", price: 5000, duration: 120, description: "Complete groom preparation package", isPopular: true },
    ],
    team: [
      { id: "t4", name: "Sultan Mehmood", role: "Master Barber & Owner", specialties: ["Precision Fades", "Beard Art"], experience: 15, image: avatars[1] },
      { id: "t5", name: "Fahad Raza", role: "Senior Stylist", specialties: ["Hair Color", "Treatments"], experience: 10, image: avatars[3] },
    ],
    timings: [
      { day: "Monday", openTime: "11:00 AM", closeTime: "11:00 PM", isClosed: false },
      { day: "Tuesday", openTime: "11:00 AM", closeTime: "11:00 PM", isClosed: false },
      { day: "Wednesday", openTime: "11:00 AM", closeTime: "11:00 PM", isClosed: false },
      { day: "Thursday", openTime: "11:00 AM", closeTime: "11:00 PM", isClosed: false },
      { day: "Friday", openTime: "03:00 PM", closeTime: "11:00 PM", isClosed: false },
      { day: "Saturday", openTime: "11:00 AM", closeTime: "12:00 AM", isClosed: false },
      { day: "Sunday", openTime: "11:00 AM", closeTime: "11:00 PM", isClosed: false },
    ],
  },
  {
    id: "3",
    name: "The Gentlemen's Corner",
    slug: "the-gentlemens-corner",
    description: "Classic gentleman's barbershop in F-7 Islamabad, providing traditional grooming services with a contemporary twist.",
    owner: "Hamza Tariq",
    phone: "+92 333 5551234",
    whatsapp: "+92 333 5551234",
    email: "gentlemen@email.com",
    address: "F-7 Markaz, Jinnah Super Market",
    city: "Islamabad",
    area: "F-7",
    latitude: 33.7294,
    longitude: 73.0631,
    rating: 4.6,
    totalReviews: 156,
    images: [shopImages[2], shopImages[0], shopImages[4]],
    coverImage: shopImages[2],
    logo: avatars[2],
    isVerified: true,
    isOpen: false,
    isPremium: false,
    badges: ["Verified"],
    createdAt: "2024-03-10",
    monthlyVisits: 780,
    qrScans: 190,
    services: [
      { id: "s14", name: "Gentleman's Cut", category: "Haircut", price: 700, duration: 35, description: "Classic gentleman's haircut", isPopular: true },
      { id: "s15", name: "Beard Grooming", category: "Beard Trim", price: 400, duration: 25, description: "Professional beard grooming", isPopular: true },
      { id: "s16", name: "Hair Wash & Style", category: "Hair Treatment", price: 500, duration: 30, description: "Shampoo, condition, and style", isPopular: false },
      { id: "s17", name: "Express Facial", category: "Facial", price: 600, duration: 30, description: "Quick refreshing facial", isPopular: false },
    ],
    team: [
      { id: "t6", name: "Hamza Tariq", role: "Owner & Barber", specialties: ["Classic Styles", "Fades"], experience: 9, image: avatars[2] },
    ],
    timings: [
      { day: "Monday", openTime: "09:00 AM", closeTime: "09:00 PM", isClosed: false },
      { day: "Tuesday", openTime: "09:00 AM", closeTime: "09:00 PM", isClosed: false },
      { day: "Wednesday", openTime: "09:00 AM", closeTime: "09:00 PM", isClosed: false },
      { day: "Thursday", openTime: "09:00 AM", closeTime: "09:00 PM", isClosed: false },
      { day: "Friday", openTime: "03:00 PM", closeTime: "09:00 PM", isClosed: false },
      { day: "Saturday", openTime: "09:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Sunday", openTime: "10:00 AM", closeTime: "08:00 PM", isClosed: false },
    ],
  },
  {
    id: "4",
    name: "Blade Masters Studio",
    slug: "blade-masters-studio",
    description: "Modern barbering studio in Saddar, Rawalpindi. Specializing in latest trends, fades, and creative hair designs.",
    owner: "Waqas Aslam",
    phone: "+92 345 6789012",
    whatsapp: "+92 345 6789012",
    email: "blade@email.com",
    address: "Shop 8, Bank Road, Saddar",
    city: "Rawalpindi",
    area: "Saddar",
    latitude: 33.5651,
    longitude: 73.0169,
    rating: 4.5,
    totalReviews: 98,
    images: [shopImages[3], shopImages[5], shopImages[1]],
    coverImage: shopImages[3],
    logo: avatars[3],
    isVerified: true,
    isOpen: true,
    isPremium: false,
    badges: ["Verified", "Trending"],
    createdAt: "2024-05-01",
    monthlyVisits: 560,
    qrScans: 120,
    services: [
      { id: "s18", name: "Fade Haircut", category: "Haircut", price: 600, duration: 35, description: "Skin fade, mid fade, or high fade", isPopular: true },
      { id: "s19", name: "Hair Design", category: "Haircut", price: 900, duration: 50, description: "Creative hair designs and patterns", isPopular: true },
      { id: "s20", name: "Beard Shape Up", category: "Beard Trim", price: 350, duration: 20, description: "Clean beard shape up", isPopular: true },
      { id: "s21", name: "Hair Straightening", category: "Hair Treatment", price: 2000, duration: 75, description: "Permanent hair straightening", isPopular: false },
    ],
    team: [
      { id: "t7", name: "Waqas Aslam", role: "Owner & Creative Barber", specialties: ["Fades", "Hair Art"], experience: 7, image: avatars[3] },
      { id: "t8", name: "Zain Malik", role: "Barber", specialties: ["Kids Cuts", "Classic"], experience: 3, image: avatars[4] },
    ],
    timings: [
      { day: "Monday", openTime: "10:00 AM", closeTime: "09:00 PM", isClosed: false },
      { day: "Tuesday", openTime: "10:00 AM", closeTime: "09:00 PM", isClosed: false },
      { day: "Wednesday", openTime: "10:00 AM", closeTime: "09:00 PM", isClosed: false },
      { day: "Thursday", openTime: "10:00 AM", closeTime: "09:00 PM", isClosed: false },
      { day: "Friday", openTime: "02:30 PM", closeTime: "09:00 PM", isClosed: false },
      { day: "Saturday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Sunday", openTime: "10:00 AM", closeTime: "09:00 PM", isClosed: false },
    ],
  },
  {
    id: "5",
    name: "Karachi Cutz",
    slug: "karachi-cutz",
    description: "Affordable quality barbershop in Clifton, Karachi. Best value for money haircuts and grooming services.",
    owner: "Imran Shah",
    phone: "+92 312 3456789",
    whatsapp: "+92 312 3456789",
    email: "karachicutz@email.com",
    address: "Block 5, Clifton",
    city: "Karachi",
    area: "Clifton",
    latitude: 24.8138,
    longitude: 67.0300,
    rating: 4.3,
    totalReviews: 187,
    images: [shopImages[4], shopImages[0], shopImages[2]],
    coverImage: shopImages[4],
    logo: avatars[4],
    isVerified: false,
    isOpen: true,
    isPremium: false,
    badges: ["Popular"],
    createdAt: "2024-02-20",
    monthlyVisits: 920,
    qrScans: 210,
    services: [
      { id: "s22", name: "Basic Haircut", category: "Haircut", price: 300, duration: 25, description: "Quick and clean haircut", isPopular: true },
      { id: "s23", name: "Combo (Cut + Beard)", category: "Haircut", price: 500, duration: 40, description: "Haircut and beard combo deal", isPopular: true },
      { id: "s24", name: "Shave", category: "Shave", price: 200, duration: 15, description: "Quick clean shave", isPopular: false },
      { id: "s25", name: "Hair Wash", category: "Hair Wash", price: 150, duration: 15, description: "Shampoo and rinse", isPopular: false },
    ],
    team: [
      { id: "t9", name: "Imran Shah", role: "Owner", specialties: ["All-round Barber"], experience: 11, image: avatars[4] },
    ],
    timings: [
      { day: "Monday", openTime: "09:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Tuesday", openTime: "09:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Wednesday", openTime: "09:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Thursday", openTime: "09:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Friday", openTime: "02:00 PM", closeTime: "10:00 PM", isClosed: false },
      { day: "Saturday", openTime: "09:00 AM", closeTime: "11:00 PM", isClosed: false },
      { day: "Sunday", openTime: "09:00 AM", closeTime: "10:00 PM", isClosed: false },
    ],
  },
  {
    id: "6",
    name: "Elite Barbers Lahore",
    slug: "elite-barbers-lahore",
    description: "Elite barbering experience in Model Town, Lahore. Where tradition meets modern grooming excellence.",
    owner: "Farhan Akbar",
    phone: "+92 300 7654321",
    whatsapp: "+92 300 7654321",
    email: "elite@email.com",
    address: "C-Block, Model Town",
    city: "Lahore",
    area: "Model Town",
    latitude: 31.4826,
    longitude: 74.3244,
    rating: 4.7,
    totalReviews: 321,
    images: [shopImages[5], shopImages[1], shopImages[3], shopImages[0]],
    coverImage: shopImages[5],
    logo: avatars[0],
    isVerified: true,
    isOpen: true,
    isPremium: true,
    badges: ["Top Rated", "Premium", "Verified"],
    createdAt: "2023-09-15",
    monthlyVisits: 1800,
    qrScans: 450,
    services: [
      { id: "s26", name: "Elite Haircut", category: "Haircut", price: 1000, duration: 40, description: "Elite signature haircut experience", isPopular: true },
      { id: "s27", name: "Royal Shave", category: "Shave", price: 500, duration: 30, description: "Royal hot towel shaving ritual", isPopular: true },
      { id: "s28", name: "Luxury Facial", category: "Facial", price: 1200, duration: 50, description: "Premium luxury facial treatment", isPopular: true },
      { id: "s29", name: "Hair Spa", category: "Hair Treatment", price: 1800, duration: 60, description: "Complete hair spa with deep conditioning", isPopular: false },
      { id: "s30", name: "Groom Package", category: "Bridal Groom", price: 4500, duration: 120, description: "Complete groom preparation", isPopular: true },
    ],
    team: [
      { id: "t10", name: "Farhan Akbar", role: "Master Barber & Owner", specialties: ["Luxury Grooming", "Bridal"], experience: 14, image: avatars[0] },
      { id: "t11", name: "Kamran Ali", role: "Senior Barber", specialties: ["Fades", "Designs"], experience: 9, image: avatars[1] },
      { id: "t12", name: "Naveed Hassan", role: "Barber", specialties: ["Classic Cuts", "Kids"], experience: 6, image: avatars[3] },
    ],
    timings: [
      { day: "Monday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Tuesday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Wednesday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Thursday", openTime: "10:00 AM", closeTime: "10:00 PM", isClosed: false },
      { day: "Friday", openTime: "02:00 PM", closeTime: "10:00 PM", isClosed: false },
      { day: "Saturday", openTime: "10:00 AM", closeTime: "11:00 PM", isClosed: false },
      { day: "Sunday", openTime: "11:00 AM", closeTime: "09:00 PM", isClosed: false },
    ],
  },
];

export const mockReviews: Review[] = [
  { id: "r1", shopId: "1", customerName: "Ali Raza", customerImage: avatars[0], rating: 5, comment: "Best haircut I've ever had in Lahore! Ahmed bhai is truly a master. The atmosphere is amazing and the service is top notch.", date: "2025-05-10" },
  { id: "r2", shopId: "1", customerName: "Hassan Malik", customerImage: avatars[1], rating: 4, comment: "Great service, very professional. The shop is clean and well maintained. Will definitely come back.", date: "2025-05-08" },
  { id: "r3", shopId: "1", customerName: "Omar Farooq", customerImage: avatars[2], rating: 5, comment: "My go-to barbershop. Consistent quality every time. Highly recommend the premium haircut package.", date: "2025-05-05" },
  { id: "r4", shopId: "2", customerName: "Zubair Ahmed", customerImage: avatars[3], rating: 5, comment: "Sultan bhai is a true artist! The hot towel shave experience is absolutely worth it. Five stars!", date: "2025-05-12" },
  { id: "r5", shopId: "2", customerName: "Fahad Khan", customerImage: avatars[4], rating: 5, comment: "Premium experience from start to finish. The grooming lounge ambiance is unmatched in Karachi.", date: "2025-05-09" },
  { id: "r6", shopId: "2", customerName: "Saad Iqbal", customerImage: avatars[0], rating: 4, comment: "Excellent service but slightly pricey. However, you get what you pay for. Quality is outstanding.", date: "2025-05-06" },
  { id: "r7", shopId: "3", customerName: "Tariq Mehmood", customerImage: avatars[1], rating: 5, comment: "Finally a proper gentleman's barbershop in Islamabad! Love the classic vibes.", date: "2025-05-11" },
  { id: "r8", shopId: "3", customerName: "Adeel Shah", customerImage: avatars[2], rating: 4, comment: "Good service and fair pricing. The location is very convenient in F-7.", date: "2025-05-07" },
  { id: "r9", shopId: "4", customerName: "Yasir Abbas", customerImage: avatars[3], rating: 5, comment: "Waqas bhai's fade game is on another level! Best fades in Rawalpindi, hands down.", date: "2025-05-10" },
  { id: "r10", shopId: "5", customerName: "Junaid Ali", customerImage: avatars[4], rating: 4, comment: "Great value for money. Quick service and decent quality. Perfect for a regular haircut.", date: "2025-05-09" },
  { id: "r11", shopId: "6", customerName: "Rizwan Chaudhry", customerImage: avatars[0], rating: 5, comment: "Elite Barbers lives up to its name. The groom package was absolutely perfect for my wedding prep.", date: "2025-05-12" },
  { id: "r12", shopId: "6", customerName: "Nasir Hussain", customerImage: avatars[1], rating: 5, comment: "Top quality service. The luxury facial is a must-try. Best barbershop experience in Lahore.", date: "2025-05-08" },
];

export const mockPricingPlans: PricingPlan[] = [
  {
    id: "free",
    name: "Free Listing",
    price: 0,
    period: "forever",
    description: "Get discovered online with a basic digital presence",
    features: [
      "Basic shop profile",
      "Up to 3 services listed",
      "Customer reviews",
      "Business hours display",
      "Basic QR code",
      "Search listing",
    ],
    isPopular: false,
    cta: "Get Started Free",
  },
  {
    id: "starter",
    name: "Starter",
    price: 200,
    period: "month",
    description: "Everything you need to grow your barber business online",
    features: [
      "Everything in Free",
      "Unlimited services",
      "Photo gallery (up to 20)",
      "Team profiles",
      "Custom QR code",
      "Priority in search",
      "WhatsApp integration",
      "Monthly analytics",
      "Verified badge",
      "Review management",
    ],
    isPopular: true,
    cta: "Start Growing",
  },
  {
    id: "premium",
    name: "Premium",
    price: 500,
    period: "month",
    description: "Full-featured platform for premium barber businesses",
    features: [
      "Everything in Starter",
      "Unlimited photos",
      "Featured listing",
      "Advanced analytics",
      "Priority support",
      "Custom branding",
      "Social media integration",
      "Promotional banners",
      "Multi-location support",
      "API access",
      "Dedicated account manager",
      "Premium badge",
    ],
    isPopular: false,
    cta: "Go Premium",
  },
];

export const mockDashboardStats: DashboardStats = {
  profileViews: 1250,
  profileViewsChange: 12.5,
  qrScans: 340,
  qrScansChange: 8.3,
  totalReviews: 234,
  reviewsChange: 5.2,
  avgRating: 4.8,
  ratingChange: 0.1,
  monthlyData: [
    { month: "Jan", views: 820, scans: 180 },
    { month: "Feb", views: 950, scans: 220 },
    { month: "Mar", views: 1100, scans: 260 },
    { month: "Apr", views: 980, scans: 240 },
    { month: "May", views: 1250, scans: 340 },
    { month: "Jun", views: 1180, scans: 310 },
  ],
};

export const mockAdminStats: AdminStats = {
  totalShops: 156,
  activeShops: 124,
  pendingApproval: 8,
  totalUsers: 1250,
  totalRevenue: 285000,
  monthlyRevenue: 48500,
  revenueData: [
    { month: "Jan", revenue: 32000, shops: 98 },
    { month: "Feb", revenue: 35000, shops: 105 },
    { month: "Mar", revenue: 42000, shops: 112 },
    { month: "Apr", revenue: 45000, shops: 118 },
    { month: "May", revenue: 48500, shops: 124 },
    { month: "Jun", revenue: 52000, shops: 130 },
  ],
};

export const mockInvoices: Invoice[] = [
  { id: "INV-001", date: "2025-05-01", amount: 200, status: "paid", plan: "Starter" },
  { id: "INV-002", date: "2025-04-01", amount: 200, status: "paid", plan: "Starter" },
  { id: "INV-003", date: "2025-03-01", amount: 200, status: "paid", plan: "Starter" },
  { id: "INV-004", date: "2025-02-01", amount: 200, status: "paid", plan: "Starter" },
];

export const mockNotifications: Notification[] = [
  { id: "n1", title: "New Review", message: "Ali Raza left a 5-star review on your shop", type: "success", read: false, date: "2025-05-12" },
  { id: "n2", title: "Profile Views Milestone", message: "Your shop crossed 1,000 profile views this month!", type: "info", read: false, date: "2025-05-10" },
  { id: "n3", title: "Subscription Renewal", message: "Your Starter plan will renew on June 1st", type: "warning", read: true, date: "2025-05-08" },
  { id: "n4", title: "New Feature", message: "You can now add team member profiles to your shop", type: "info", read: true, date: "2025-05-05" },
];
